version: '3'

services:
 smlmis:
  container_name: sml_mis
  restart: always
  image: smlsoft/mis:2
  expose:
   - 8080
  volumes:
   - /data/sml/tomcat/temp:/usr/local/tomcat/temp
  networks:
   - backend
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=sml_service_network"
   - "traefik.frontend.rule=PathPrefix:/mis"
networks:
 backend:
  external:
   name: sml_service_network

