version: '3'

services:
  traefik_proxy:
    image: traefik:1.7
    container_name: traefik_proxy
    restart: always
    ports:
     - 8088:8080 ## monitor
     - 8080:80 ## http
    volumes:
     - ./traefik.toml:/etc/traefik/traefik.toml
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - backend
networks:
  backend:
   external:
     name: sml_service_network
